### ISSUE TITLE
Not working on java 9

### ISSUE THREAD

**Issue by NicklasMCHD** [ultraq/preferences-xml#3]
Hi.
I'm using this bindind for xml (together with your normal preferences library) and when I upgrade to Java 9 (jdk 9.0.1) every time I try to interface with your library my ide (Eclipse( pops up with a dialog saying:
Unexpected build errors while building project.
When I then show details I cann see that it is something about the JavaServiceLoader and a NullPointerException when the JavaServiceLoader tries to load your service from the PreferencesXML library.

OS:
Windows 10 64 bit.

I don't know whats wrong but I think that they removed the JavaServiceLoader or changed the way reflection is made in Java 9.
Hope you can fix it.

**Comment by ultraq** [comment]
Hmm, I better check that out.  I haven't even installed Java 9, but I do have a few "check it works on Java 9" issues to run through.  I'll add this to the list to check.

**Comment by NicklasMCHD** [comment]
Hi @ultraq
Do you have any updates as to if you can get it to work with Java 9?

**Comment by ultraq** [comment]
No thing sorry, but the earliest I'll be able to start looking at this will be this weekend, so hopefully I'll have something more to say after then.  I'll be posting any updates here.

**Comment by ultraq** [comment]
I've finally had a chance to look at this and I did find problems when running it in a Java 9 environment, but nothing that mentions JavaServiceLoader, so I hope what I've got helps with your situation.

For the problem I found, I've learned that in Java 9 they deprecated all `javax.*` packages from Java SE (slated for removal in Java 10) which are now only accessible [via special command-line flags like `--add-modules java.xml.bind`](https://blog.codefx.org/java/five-command-line-options-to-hack-the-java-9-module-system/#Extending-The-Module-Graph-With--add-modules).  The particular dependency this library is having trouble with is the Java Activation Framework (`javax.activation` package).

As a workaround, you could add the `--add-modules java.activation` option to  to the command line flags when running your program.  But that's not always ideal in an IDE situation, so I've also published a `1.2.3-SNAPSHOT` version of this library to the Maven snapshots repository which includes the separated JAF dependency.  Would you be able to give that snapshot version a try?

The long-term solution though is to update this project and all its dependencies to use Java 9 versions of the `javax.*` packages.  That'll require a bit more work and a bigger release, so I'm hoping the quick patch works!

**Comment by NicklasMCHD** [comment]
Hi.
I'll take a look at it. I think that you also need to update your other library ( https://github.com/ultraq/preferences ) with the same patch to get it to work, but I'm not sure.
I'll test it once I know if you need to update the other library as well.

**Comment by JessicaTegner** [comment]
Do you have any news about the support for Java 9? @ultraq

**Comment by ultraq** [comment]
Yup, although did the `1.2.3-SNAPSHOT` version work for you?

I also released a 2.0.0 version (where I pushed the fix that was in snapshot version down to one of the dependencies that actually needed it) that has the CI build running against Java 9 and that seemed to work as well, so you have 2 options for upgrading if you want to try either.

**Comment by JessicaTegner** [comment]
It seams to be working now. But it gets detected as an automatics module. To fix that issue add a module-info in the src root (that also counts for https://github.com/ultraq/preferences )

**Comment by ultraq** [comment]
Yup, for now, an "automatic" module will do.  I'm still learning about the new module spec and, across all my projects, figuring out what I need to export/provide/require.  A proper module descriptor will come in a later release.
